package com.fitness.backend.enums;

public enum ExerciseName {
    // Legs
    SQUAT,
    FRONT_SQUAT,
    DEADLIFT,
    ROMANIAN_DEADLIFT,
    LEG_PRESS,
    LUNGES,
    SPLIT_SQUAT,
    HIP_THRUST,
    LEG_EXTENSION,
    LEG_CURL,
    CALF_RAISE,

    // Chest
    DECLINE_BENCH_PRESS,
    FLAT_BENCH_PRESS,
    INCLINE_BENCH_PRESS,
    DUMBBELL_FLY,
    CABLE_FLY,
    PEC_DECK,
    DECLINE_DUMBBELL_PRESS,
    FLAT_DUMBBELL_PRESS,
    INCLINE_DUMBBELL_PRESS,

    // Back
    BARBELL_ROW,
    DUMBBELL_ROW,
    PENDLAY_ROW,
    LAT_PULLDOWN,
    SEATED_ROW_WIDE,
    SEATED_ROW_NARROW,
    SHRUG,

    // Shoulders
    OVERHEAD_MACHINE_PRESS,
    OVERHEAD_DUMBBELL_PRESS,
    LATERAL_RAISE,
    FRONT_RAISE,
    REAR_DELT_FLY,
    ARNOLD_PRESS,

    // Arms
    BICEP_CURL,
    HAMMER_CURL,
    PREACHER_CURL,
    TRICEP_EXTENSION,
    CABLE_TRICEP_PUSHDOWN,
    DUMBBELL_TRICEP_KICKBACK
}
