spring:
  application:
    name: backend

  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: "5c0bd8a285d51ea264e0febb57a04cc69bb0f807e6c60484f010cc615dd1cdee"
  expiration: 86400000